req_lev:
  - M
  - HR
  - R
  - O
sample_type:
  - Water
assay_type: metabarcoding
project_id: noaa-aoml-gomecc4
assay_name:
  - ssu16sv4v5-emp
  - ssu18sv9-emp
projectMetadata_user:
  # - user_defined_project_field_1
  # - user_defined_project_field_2

sampleMetadata_user:
  # - user_defined_sample_field_1
  # - user_defined_sample_field_2
experimentRunMetadata_user:
  # - user_defined_experiment_run_field_1
    
