name: fairesheets-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - pyyaml
  - numpy
  - pip
  - pip:
    - python-dotenv
    - google-auth
    - gspread
    - gspread_formatting 