# This config file is for FAIRe2NODE (to be run after FAIReSheets)
# It is used to set parameters for the FAIRe2NODE run

# Required: Project ID (must match the project_id used in FAIReSheets)
project_id: "your_project_id_here"

# Optional: Analysis run names and their corresponding assay names
# If not provided, a generic analysisMetadata sheet will be created
# Use the exact analysis_run_name and assay_name values from your NOAA checklist
analysis_run_name:
  gomecc_4_16s:  # This is the analysis_run_name from your NOAA checklist
    assay_name: "16S"  # This is the assay_name from your NOAA checklist
  # Add more analysis runs as needed, using the exact names from your NOAA checklist
  gomecc_4_18s:
    assay_name: "18S"
