# This config file is for FAIRe2NODE (to be run after FAIReSheets)
# It is used to set parameters for the FAIRe2NODE run

# Required: Project ID (must match the project_id used in FAIReSheets)
project_id: "noaa-aoml-gomecc4"

#-----------------------------------------------------------------

# If you DO NOT have any analysis runs ready:
# Use the following to generate a generic analysisMetadata sheet:

analysis_run_name:
  "analysisMetadata_<analysis_run_name>":
    assay_name: ""
#-----------------------------------------------------------------

# If you DO have analysis runs ready:
# To use specific analysis run names, uncomment and modify:
#
#   gomecc4_16s_p1-2_v2024.10_241122:
#     assay_name: "ssu16sv4v5-emp"
#   # Add more analysis runs as needed
#   gomecc4_16s_p3-6_v2024.10_241122:
#     assay_name: "ssu16sv4v5-emp"
#   gomecc4_18s_p1-6_v2024.10_241122:
#     assay_name: "ssu18sv9-emp"

#-----------------------------------------------------------------
